### ISSUE TITLE
NPM has incorrect information

### ISSUE THREAD

**Issue by apankDocero** [DigitalRockers/semrush#3]
It should say 'semrush-api' but it says 'semrush' which causes errors and cause you to download the wrong [library](https://www.npmjs.com/package/semrush) if you only view it on npmjs.com and not github.

<img width="409" alt="screen shot 2016-09-27 at 10 21 04 pm" src="https://cloud.githubusercontent.com/assets/22234532/18898657/fe721cbe-8500-11e6-88b2-b4d8699c6b33.png">
<img width="293" alt="screen shot 2016-09-27 at 10 20 57 pm" src="https://cloud.githubusercontent.com/assets/22234532/18898656/fe6fdaf8-8500-11e6-9814-827038f02375.png">

**Comment by gian788** [comment]
Thank you @apankDocero, I've updated the npm package.
